import:
  - ~/.config/alacritty/catppuccin/catppuccin-mocha.yml

live_config_reload: true

env:
  TERM: xterm-256color

window:
  decorations: buttonless
  opacity: 1.0
  dynamic_padding: false
  padding:
    x: 25
    y: 20

font:
  normal:
    family: "JetBrainsMono Nerd Font"
    style: Light
  italic:
    family: "JetBrainsMono Nerd Font"
    style: Medium Italic
  bold:
    family: "JetBrainsMono Nerd Font"
    style: Heavy
  bold_italic:
    family: "JetBrainsMono Nerd Font"
    style: Heavy Italic
  size: 15.0 

key_bindings:
  - { key: Right, mods: Alt, chars: "\x1BF" }
  - { key: Left,  mods: Alt, chars: "\x1BB" }
  - { key: E, mods: Command, chars: "\x01\"" } # split tmux window vertically
  - { key: E, mods: Command|Shift, chars: "\x01%" } # split tmux window horizontally
  - { key: T, mods: Command, chars: "\x01c" } # create a new tmux window
  - { key: W, mods: Command, chars: "\x01x" } # kill the current pane
